language: python

python:
    - "3.6"
    
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    - pytest
    - coverage run -m py.test

after_success:
- codecov

